trigger:
  - main

pool:
  name: Azure Pipelines
  vmImage: windows-2022

variables:
  BASE_VERSION: 0.3.0
  BUILD_NUMBER: $[counter(format('{0}_{1}', variables['BASE_VERSION'], variables['Build.SourceBranch']), 1)]
  PACKAGE_VERSION: $(BASE_VERSION).$(BUILD_NUMBER)
  CONFIGURATION: 'Release'
  BUILD_PRERELEASE: false
  DOTNET_CORE_VERSION: 8.x

steps:
  - task: UseDotNet@2
    inputs:
      version: $(DOTNET_CORE_VERSION)
      performMultiLevelLookup: true
  - powershell: dotnet tool restore
  - powershell: dotnet cake --configuration="$(CONFIGURATION)" --packageVersion="$(PACKAGE_VERSION)" --prerelease="$(BUILD_PRERELEASE)"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: output
      artifactName: nuget
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: 'Mono.ApiTools.*.Tests\**\*.trx'
