trigger:
  - main

pool:
  name: Azure Pipelines
  vmImage: windows-2022

variables:
  BASE_VERSION: 0.5.0
  BUILD_NUMBER: $[counter(format('{0}_{1}', variables['BASE_VERSION'], variables['Build.SourceBranch']), 1)]
  PACKAGE_VERSION: $(BASE_VERSION).$(BUILD_NUMBER)
  CONFIGURATION: 'release'
  BUILD_PRERELEASE: true
  DOTNET_CORE_VERSION: 9.x

steps:
  - task: UseDotNet@2
    displayName: Install .NET
    inputs:
      version: $(DOTNET_CORE_VERSION)
      performMultiLevelLookup: true
  - pwsh: dotnet tool restore
    displayName: Restore .NET tools
  - pwsh: dotnet cake --configuration="$(CONFIGURATION)" --packageVersion="$(PACKAGE_VERSION)" --prerelease="$(BUILD_PRERELEASE)"
    displayName: Build, pack and test everything
  - publish: artifacts/package/release
    artifact: nuget
    displayName: Upload artifacts
  - task: PublishTestResults@2
    displayName: Upload test results
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: 'Mono.ApiTools.*.Tests\**\*.trx'
